name: firebasseeee
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.8.0
  google_fonts:  6.2.1
  get:
  get_storage: ^2.1.1
  firebase_auth:
  firebase_core:
  firebase_storage:
  cloud_firestore: ^5.6.4
  cupertino_icons: ^1.0.8
  google_sign_in: ^6.2.2
  random_string: ^2.3.1
  gesture_x_detector: ^1.1.1
  supabase_flutter: ^2.8.3
  intl:
  image_picker:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true